apiVersion: "pipelinesascode.tekton.dev/v1alpha1"
kind: Repository
metadata:
  name: rade5k4s4-dotnet-basic-gitops-repository
spec:
  url: https://github.com/rhtap-rhdh-qe/rade5k4s4-dotnet-basic-gitops