apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  argocd/app-name: rade5k4s4-dotnet-basic
  janus-idp.io/tekton: rade5k4s4-dotnet-basic
  backstage.io/kubernetes-id: rade5k4s4-dotnet-basic
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: rade5k4s4-dotnet-basic
resources:
  - deployment.yaml
  - route.yaml
  - service.yaml
